# Generated by Django 4.0.3 on 2022-04-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
